# Basic Information 
title: Xiangjun Tan
position: 5th Year Physics Honours Student
affiliation: University of New South Wales
email: xiangjun.tan@student.unsw.edu.au

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: UNSW RSA, Xiangjun Tan, 谈相君, Quantum Computing, xiangjun tan
description: Welcome to the personal website of Xiangjun Tan, featuring insights and publications on Quantum Tech and Condensed Matter, updates on ongoing projects, and professional milestones.
canonical: https://xiangjun-tan.github.io
#google-site-verification=RZLA2MKX92M15lOSpbbR5Ca5rSuPSv9rQcqMlr8liUk
# Baidu Webmaster tools verification.
# See: https://ziyuan.baidu.com/site
baidu_site_verification: true

# Enable baidu push so that the blog will push the url to baidu automatically which is very helpful for SEO.
baidu_push: true  

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/
cv_link: assets/files/resume.pdf
github_link: https://github.com/xiangjun-tan
linkedin: https://www.linkedin.com/in/xiangjun-tan-30188b22a?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/avatar.png
favicon: ./assets/img/avatar.jpg
favicon_dark: ./assets/img/avatar.jpg

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: true

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"

# Google Analytics ID
# Please remove this if you don't use Google Analytics
#google_analytics: UA-111540567-4

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
